security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    user_provider:
      id: App\Security\Core\User\UserProvider

  firewalls:
    register:
      pattern: ^/api/v1/register
      methods: [POST]
      security: false

    login:
      pattern: /api/v1/login
      stateless: true
      anonymous: true
      provider: user_provider
      json_login:
        check_path: /api/v1/login-check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    api:
      pattern: ^/api/v1
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }
